FROM apachesuperset.docker.scarf.sh/apache/superset:6.0.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       default-libmysqlclient-dev \
       pkg-config \
       build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN uv pip install --python /app/.venv/bin/python \
    PyMySQL \
    mysqlclient

USER superset
